### ISSUE TITLE
Popover in Dialog

### ISSUE THREAD

**Issue by ArizonaInkStudios** [ng-matero/extensions#173]
Hello first time writer, short time user, forever lover of these components.

I noticed when using the popover in a dialog that is already inside a cdk-overlay-container, when the popover gets created, it creates an additional cdk-overlay-[1, 2, 3, etc] infinitely. It does not show the popover at all. It also does not clean up the newly created cdk-overlay-{number} and so the DOM gets polluted with an infinite number of empty cdk-overlays.

There is a possibly I am doing something wrong. Has this been asked and/or discovered in the past? Any thoughts?

Thank you again for such an amazing suite of components.

_Attached image is of the DOM after hovering over a popover inside the mat-dialog._
![image](https://user-images.githubusercontent.com/24530979/212481361-2498afe9-5dae-4ff6-b4c4-53b4fbcfe911.png)

**Comment by ArizonaInkStudios** [comment]
Further debugging leads to the following in the console:

ERROR TypeError: Cannot read properties of undefined (reading 'listen')
    at TransitionAnimationEngine.listen (browser.mjs:3428:53)
    at InjectableAnimationEngine.listen (browser.mjs:4353:39)
    at AnimationRenderer.listen (animations.mjs:342:32)
    at listenerInternal (core.mjs:14907:40)
    at ɵɵlistener (core.mjs:14788:5)
    at MtxPopover_ng_template_0_Template (mtxPopover.mjs:461:1354)
    at executeTemplate (core.mjs:11242:9)
    at renderView (core.mjs:11064:13)
    at TemplateRef.createEmbeddedView (core.mjs:22374:9)
    at ViewContainerRef.createEmbeddedView (core.mjs:22492:37)

**Comment by ArizonaInkStudios** [comment]
Nevermind, it WAS something bad I was doing. I apologize for taking up your time! Keep up the great work and I look forward to continue usage of these amazing components.
