### ISSUE TITLE
Data Grid with server side rendering

### ISSUE THREAD

**Issue by ng-alynasser** [ng-matero/extensions#50]
const hasNativeClosest = !!Element.prototype.closest;
                         ^

ReferenceError: Element is not defined
    at Module.EePR (C:\Users\User\edura-web\dist\edura-web\server\main.js:79647:26)
    at __webpack_require__ (C:\Users\User\edura-web\dist\edura-web\server\main.js:26:30)
    at Module.q+7u (C:\Users\User\edura-web\dist\edura-web\server\main.js:229482:96)
    at __webpack_require__ (C:\Users\User\edura-web\dist\edura-web\server\main.js:26:30)
    at Module.wQKi (C:\Users\User\edura-web\dist\edura-web\server\main.js:260908:97)
    at __webpack_require__ (C:\Users\User\edura-web\dist\edura-web\server\main.js:26:30)
    at Module.hGDI (C:\Users\User\edura-web\dist\edura-web\server\main.js:194221:103)
    at __webpack_require__ (C:\Users\User\edura-web\dist\edura-web\server\main.js:26:30)
    at Module.ld3Y (C:\Users\User\edura-web\dist\edura-web\server\main.js:215266:89)
    at __webpack_require__ (C:\Users\User\edura-web\dist\edura-web\server\main.js:26:30)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:64521

**Comment by nzbin** [comment]
Maybe extensions has not supported SSR yet.
